### ISSUE TITLE
Feature request - named IPs

### ISSUE THREAD

**Issue by jamesrward** [jcottrell/ServerIP#3]
It would be very useful if I could assign names to a couple of ip addresses via a preference setting.  Staying within the 3 character limit wouldn't be a problem.  My idea would be to have certain ips come up with "dev" for example instead of the "255".  Please let me know if your interested in working on this and maybe we can make arrangements for me to reimburse you for your time.

**Comment by jcottrell** [comment]
Great idea James. I'll see what I can get done. It would be useful for me too so no need for compensation.

**Comment by jcottrell** [comment]
Just updated everything. It seems to be working over here. Let me know if you have any problems.
