### ISSUE TITLE
Feature request: copy IP address to clipboard

### ISSUE THREAD

**Issue by jamesrward** [jcottrell/ServerIP#4]
Love the mnemonic addition but the floating ip address on the page has left me with no way to easily copy the ip address to the clipboard.  This was simple in the previous version as I could just click on the icon highlight the ip and hit ctrl+v,  it is a feature I sorely miss.

**Comment by jcottrell** [comment]
I'll get right on it sir. Thanks for the feedback.

**Comment by jcottrell** [comment]
Still working James. Things got a lot busier around here so I'll have to get back to you later, by end of September probably.
